AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  amberproj

  Sample SAM Template for amberproj

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  TableName:
    Type: String
    Default: "hitinfo"
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: "Required parameter. Must be characters only. No numbers allowed."
Globals:
  Function:
    Timeout: 30
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'POST, GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"  

Resources:
  RandomGeneratoFun:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: hello_world/
        Handler: app.random_bundle
        Runtime: python3.8
        Policies:
          - DynamoDBCrudPolicy:
              TableName: 'raw'
        Events:
          HelloWorld:
            Type: Api 
            Properties:
              Path: /random
              Method: GET
  AmberFun:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.post_item
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /newitem
            Method: POST
  AmberGetListFun:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.get_list
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        GetList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getlist
            Method: GET
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AmberFunApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AmberFun:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AmberFun.Arn
  AmberFunIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AmberFunRole.Arn
