AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  amberproj

  Sample SAM Template for amberproj

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  HitDataTable:
    Type: String
    Default: "generationalData"
  RawData:
    Type: String
    Default: "raw"

Globals:
  Function:
    Timeout: 30
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'POST, GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  RandomGeneratorFun:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: app.random_bundle
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "raw"
      Events:
        RandomGeneratorRequest:
          Type: Api
          Properties:
            Path: /random
            Method: GET
  GenerationalBundleGetter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: random_generational_bundle.random_generational_response
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RawData
        - DynamoDBCrudPolicy:
            TableName: !Ref HitDataTable
      Events:
        GenerationalBundleRequest:
          Type: Api
          Properties:
            Path: /generational_bundle
            Method: GET
  PostItemsFun:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      Handler: app.post_item
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HitDataTable
      Events:
        PostItem:
          Type: Api
          Properties:
            Path: /newitem
            Method: POST

  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref HitDataTable
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: persona_id
          AttributeType: N
        - AttributeName: generation
          AttributeType: N

      KeySchema:
        - AttributeName: itemId
          KeyType: HASH

      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: PersonaIndex
          KeySchema:
            - AttributeName: persona_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: GenerationIndex
          KeySchema:
            - AttributeName: generation
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PostItemsFunApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/newitem/"
  PostItemsFun:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PostItemsFun.Arn
  PostItemsFunIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PostItemsFunRole.Arn
